### ISSUE TITLE
install script doesn't copy the wallpapers in the correct dir

### ISSUE THREAD

**Issue by avivi55** [JaKooLit/Hyprland-v2.1#2]
## Problem
the script doesn't create the `~/Pictures/wallpapers` folder so at boot the wallpaper is just black.

## Fix
original:
```bash
645    mkdir -p ~/Pictures
646    cp -r wallpapers ~/Pictures/ || { echo "Error: Failed to copy wallpapers."; exit 1; } 2>&1 | tee -a "$LOG"
```
fix :
```bash
645    mkdir -p ~/Pictures && mkdir -p ~/Pictures/wallpapers
646    cp -r wallpapers ~/Pictures/wallpapers || { echo "Error: Failed to copy wallpapers."; exit 1; } 2>&1 | tee -a "$LOG"
```

it's a guess, but I think it works.

**Comment by JaKooLit** [comment]
Ok Ive edited the script to create wallpapers folder and ensuring that copying of wallpapers is completed before proceeding to next step
