### ISSUE TITLE
update `cheatsheet.md` - find `hwmon path` quickly

### ISSUE THREAD

**Issue by jqtmviyu** [JaKooLit/Hyprland-v2.1#3]
```sh
for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
```

**Comment by jqtmviyu** [comment]
Duplicate settings:

https://github.com/JaKooLit/Hyprland-v2.1/blob/2143652eab458526c2c43b540dd4da6a3eb3da2e/config/hypr/hyprland.conf#L14

https://github.com/JaKooLit/Hyprland-v2.1/blob/2143652eab458526c2c43b540dd4da6a3eb3da2e/config/hypr/hyprland.conf#L69

It might be better to put the same project configuration together, instead of overwriting

**Comment by JaKooLit** [comment]
I have added into cheatsheet the command to find hwmon path. Much appreciated.

I have also edited the hyprland.conf to remove the layout = master. Didnt notice that and luckily didnt cause any issues. And that I really appeciated it as well. Thank you very much
