### ISSUE TITLE
Establishing connection to PulseAudio

### ISSUE THREAD

**Issue by jqtmviyu** [JaKooLit/Hyprland-v2.1#5]
## Problem
When I right-click on the volume icon on the bar, it prompts to `Establishing connection to PulseAudio`

## What have I done

run install shell  after  base arch  system instelled, and not choice `Bluetooth packages`

### Check packages is installed

`pipewire-alsa`, `pipewire-pulse`, `wireplumber`, `pavucontrol`

### unmute channel

```sh
amixer set Master unmute
```

Manual set

```sh
alsamixer
```

`MM` symbol means mute, press the `m` key to unmute

### Setting the default sound card

View sound card information

```sh
aplay -l
```

Set for current user

```
vim ~/.asoundrc

===like this
defaults.pcm.card 1
defaults.pcm.device 0
defaults.ctl.card 1
===
```

for all users , path is `/etc/asound.conf`

### Finally

restart and tyr again

**Comment by JaKooLit** [comment]
thank you for sharing

**Comment by jqtmviyu** [comment]
I'm not sure if `pipewire-alsa pipewire-pulse` were installed in the script when `Bluetooth` was not selected for installation.

```
yay -Qi pipewire-alsa

===

Depends On      : pipewire  pipewire-audio  pipewire-session-manager
Required By     : None

===

yay -Qi pipewire-pulse

===

Depends On      : libavahi-client.so=3-64  libavahi-common.so=3-64  libglib-2.0.so=0-64  libpipewire-0.3.so=0-64
                  libpulse.so=0-64  pipewire  pipewire-audio  pipewire-session-manager
Required By     : None

===

yay -Qi wireplumber

===
Depends On      : libwireplumber=0.4.14-1  libsystemd.so=0-64  lua  pipewire
Required By     : pipewire-alsa  pipewire-pulse  waybar-hyprland-git
===

yay -Qi pavucontrol

===
Depends On      : gtkmm3  libsigc++  libcanberra  json-glib
Required By     : None
===
```

 https://github.com/JaKooLit/Hyprland-v2.1/blob/980a4c3dc3b3b928385de90fc5b3eccb546d1d56/install-hyprland-2.1#L265

here install `pavucontrol`

`waybar-hyprland-git`  will import  `wireplumber` , seem not found  `pipewire-pulse`  `pipewire-alsa`

**Comment by JaKooLit** [comment]
I will add the pipewire-alsa on the script. The pipewire-pulse will be pulled by pavucontrol
