### ISSUE TITLE
Mako dark/light config missing

### ISSUE THREAD

**Issue by KorigamiK** [JaKooLit/Hyprland-v2.1#8]
https://github.com/JaKooLit/Hyprland-v2.1/blob/5c7dcd4a83646c9fbbe6e6a318915a7541919f5e/config/hypr/scripts/dark-light-mode#L33

Maybe this is just a mishap but this line should be removed if there is no separate config for mako for light and dark mode

**Comment by JaKooLit** [comment]
Thanks alot. Indeed you are correct as it has no separate config. I have also remove the line for wofi.

**Comment by JaKooLit** [comment]
Thanks alot. Indeed you are correct as it has no separate config. I have also remove the line for wofi.
