### ISSUE TITLE
Add hyprland project for void linux ?

### ISSUE THREAD

**Issue by mjcc30** [JaKooLit/Hyprland-v2.1#9]
Hi nice work !
Is it possible for you to do this for void linux pls ?
I only tried hyprland on a overclocked rpi4 and its working great.
But i have somme trouble to add your rice.
So i decided to test in a VM but same results
I can give you some ressources to make hyprland work if you need

**Comment by JaKooLit** [comment]
atm, I dont have plan since

1.) Im not 100% into none-systemd distros since im used to it.

in theory, it should be fairly easy to install / add configs into any distros

I have moved into centralized dots

https://github.com/JaKooLit/Hyprland-Dots
